#!/bin/bash

curl -LSs https://github.com/multiarch/qemu-user-static/releases/download/v5.0.0-2/x86_64_qemu-aarch64-static.tar.gz | tar xzv

docker run --rm --privileged multiarch/qemu-user-static:register --reset
